import type { Metadata } from "next";
import {
  Geist,
  Geist_Mono,
  Space_Grotesk,
  Bebas_Neue,
  DM_Sans,
} from "next/font/google";
import "./globals.css";
import Cursor from "./components/Cursor";
import RevealObserver from "./components/RevealObserver";

// const bebasNeue = Bebas_Neue({
//   variable: "--font-bebas-sans",
//   subsets: ["latin"],
// });

const bebasNeue = Bebas_Neue({
  variable: "--font-bebas-neue",
  subsets: ["latin"],
  weight: "400",
});

const dmSans = DM_Sans({
  variable: "--font-dm-sans",
  subsets: ["latin"],
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const spaceGrotesk = Space_Grotesk({
  variable: "--font-space-grotesk",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "BloomPoint",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} ${spaceGrotesk.variable} ${bebasNeue.variable} ${dmSans.variable}  h-full antialiased`}
    >
      <body className="min-h-full flex flex-col cursor-none">
        <Cursor />
        <RevealObserver />
        {children}
      </body>
    </html>
  );
}
